package com.mineserve.mobile.server

import com.mineserve.mobile.runtime.TermuxRuntime
import java.io.File

/**
 * server.properties 文件读写解析器。
 *
 * - 标准格式：`#` 开头为注释，`key=value` 每行一个
 * - 手动逐行解析（不使用 java.util.Properties，避免破坏顺序与类型）
 * - 服务器未首次启动时该文件可能不存在，readProperties 返回空 Map
 *
 * @param termux Termux 运行时，用于定位 server 目录
 */
class ServerPropertiesManager(private val termux: TermuxRuntime) {

    /** server.properties 文件路径：home/servers/{dirName}/server.properties */
    private fun propertiesFile(dirName: String): File =
        File(termux.installer.rootDir, "home/servers/$dirName/server.properties")

    fun propertiesPath(dirName: String): File = propertiesFile(dirName)

    fun configPaths(dirName: String, powerNukkitX: Boolean): List<File> {
        val dir = propertiesFile(dirName).parentFile ?: return emptyList()
        return if (powerNukkitX) PowerNukkitXLayout.configFiles(dir) else listOf(propertiesFile(dirName))
    }

    /**
     * 读取所有属性为 Map<String,String>。
     *
     * - 文件不存在返回空 Map
     * - 跳过 `#` 注释行和空行
     * - 仅按第一个 `=` 分割（值本身可能含有 `=`）
     * - 保持文件中的出现顺序（LinkedHashMap）
     */
    fun readProperties(dirName: String): Map<String, String> {
        val file = propertiesFile(dirName)
        if (!file.exists()) return emptyMap()
        val result = LinkedHashMap<String, String>()
        return try {
            file.readLines().forEach { rawLine ->
                val line = rawLine.trim()
                // 跳过空行与注释行
                if (line.isEmpty() || line.startsWith("#")) return@forEach
                val eq = line.indexOf('=')
                // 没有 = 或 = 在行首（key 为空）则跳过
                if (eq <= 0) return@forEach
                val key = line.substring(0, eq).trim()
                // 值取 = 之后全部内容（只分割第一个 =），并去除首尾空白
                val value = line.substring(eq + 1).trim()
                if (key.isNotEmpty()) result[key] = value
            }
            result
        } catch (e: Exception) {
            emptyMap()
        }
    }

    /**
     * 写入属性（覆盖整个文件）。
     *
     * - 文件头部加注释说明由 MineServeMobile 生成
     * - 每个属性一行 `key=value`
     * - 文件不存在时自动创建父目录（parentFile.mkdirs）
     * - 成功返回 true，失败返回 false
     */
    fun writeProperties(props: Map<String, String>, dirName: String): Boolean {
        val file = propertiesFile(dirName)
        return try {
            file.parentFile?.mkdirs()
            val sb = StringBuilder()
            sb.append("# Minecraft server properties\n")
            sb.append("# Generated by MineServeMobile\n")
            sb.append("# Edit via MineServeMobile UI\n")
            props.forEach { (key, value) ->
                sb.append(key).append('=').append(value).append('\n')
            }
            file.writeText(sb.toString())
            true
        } catch (e: Exception) {
            false
        }
    }

    /**
     * 读取单个属性。
     *
     * - 文件不存在或 key 不存在时返回 [default]
     */
    fun getProperty(key: String, dirName: String, default: String = ""): String {
        return readProperties(dirName)[key] ?: default
    }
}
